org: # The name of your serverless organization
app: aws-lambda-oauth-authorizer2 # Name of the application
service: aws-lambda-oauth-authorizer2 # Name of the connected service

provider:
  name: aws
  region: eu-west-1
  stackTags:
    "tg:service": 'gateway-auth'
    "tg:team": "platform"

useDotenv: true

plugins:
  - serverless-webpack

functions:
  authorizer:
    name: ${sls:stage}-gateway-serverless-authorizer
    handler: src/index.handler
    runtime: nodejs16.x

package:
  patterns:
    - ".env"
